#rhevm:
#  name: RHEV-M

ec2:
  name: Amazon EC2

#rackspace:
#  name: RackSpace

#gogrid:
#  name: GoGrid

#vmware_esx:
#  name: VMWare ESX

# For development, just uncomment this target to do fake image builds
#mock:
#  name: Mock