fedora:
  name: Fedora
  baseurl: http://download.fedoraproject.org/pub/fedora/linux/releases/11/Everything/x86_64/os/
rhel:
  name: RHEL
  # this should be ignored, it's defined just to be showned in selection tag
  baseurl: http://download.fedoraproject.org/pub/fedora/linux/releases/11/Everything/x86_64/os/
