-
  id: fedora13
  name: Fedora
  baseurl: http://download.fedoraproject.org/pub/fedora/linux/releases/13/Fedora/x86_64/os/
  type: xml
  install: true
  platform_id: fedora13

-
  id: fedora14
  name: Fedora
  baseurl: http://download.fedoraproject.org/pub/fedora/linux/releases/14/Fedora/x86_64/os/
  type: xml
  install: true
  platform_id: fedora14

-
  id: aeolus-custom
  name: Aeolus-custom
  baseurl: http://repos.fedorapeople.org/repos/aeolus/demo/webapp/
  type: xml
  platform_id: fedora14

# you can define multiple repositories, as array, for example:
#
# -
#   id: repo1
#   name: Repo
#   baseurl: url
#   type: xml
#
# -
#   baseurl: https://admin:admin@localhost/pulp/api/
#   yumurl: https://localhost/pulp/repos/
#   type: pulp
