fedora:
  name: Fedora
  baseurl: http://download.fedoraproject.org/pub/fedora/linux/releases/11/Everything/x86_64/os/
jboss:
  name: JBoss
  baseurl: http://repo.oddthesis.org/cirras/packages/fedora/11/RPMS/noarch/
